services:

  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.8.0'
    container_name: 'zookeeper'
    restart: 'unless-stopped'
    ports:
      - '2181:2181'
    environment:
      - 'ZOOKEEPER_CLIENT_PORT=2181'
    healthcheck:
      test: 'echo stat | nc localhost $$ZOOKEEPER_CLIENT_PORT'

  kafka:
    image: 'confluentinc/cp-kafka:7.8.0'
    container_name: 'kafka'
    restart: 'unless-stopped'
    depends_on:
      - 'zookeeper'
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      - 'KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      - 'KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]

  schema-registry:
    image: 'confluentinc/cp-schema-registry:7.8.0'
    container_name: 'schema-registry'
    restart: 'unless-stopped'
    depends_on:
      - 'kafka'
    ports:
      - '8081:8081'
    environment:
      - 'SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:9092'
      - 'SCHEMA_REGISTRY_HOST_NAME=schema-registry'
      - 'SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081'
    healthcheck:
      test: 'curl -f http://localhost:8081 || exit 1'

  schema-registry-ui:
    image: 'landoop/schema-registry-ui:0.9.5'
    container_name: 'kafka-schema-registry-ui'
    restart: 'unless-stopped'
    depends_on:
      - 'schema-registry'
    ports:
      - '8001:8000'
    environment:
      - 'SCHEMAREGISTRY_URL=http://schema-registry:8081'
      - 'PROXY=true'
    healthcheck:
      test: 'wget --quiet --tries=1 --spider http://localhost:8000 || exit 1'

  kafdrop:
    image: 'obsidiandynamics/kafdrop:4.1.0'
    container_name: 'kafdrop'
    restart: 'unless-stopped'
    depends_on:
      - 'kafka'
    ports:
      - '9000:9000'
    environment:
      - 'KAFKA_BROKERCONNECT=kafka:9092'
    healthcheck:
      test: 'curl -f http://localhost:9000 || exit 1'